language: go
go:
- "1.11"

services:
- docker

jobs:
  include:
  - stage: build image
    services:
    - docker
    before_script:
    - echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
    script:
    - docker build -t bombergame/rest-api-reference .
    after_success:
    - if [ ${TRAVIS_BRANCH} = "master" ]; then
      docker push bombergame/rest-api-reference;
      fi

  - stage: deploy
    addons:
      apt:
        packages:
        - npm
    before_script:
    - npm install now -g
    script:
    - if [ ${TRAVIS_BRANCH} = "master" ]; then
      now --token ${NOW_TOKEN} && now alias --token ${NOW_TOKEN};
      fi
